import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Logic Computers</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Logic Computers
        </h1>

        <p className={styles.description}>
          We repair,upgrade and sell computers.
        </p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Printers &rarr;</h2>
            <p>Find all the printer offers</p>
          </a>

          <a href="#" className={styles.card}>
            <h2>Laptops &rarr;</h2>
            <p>Deep dive into laptop world</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Computers &rarr;</h2>
            <p>We got you to get the best deals for computers</p>
          </a>

          <a
            href="#"
            className={styles.card}
          >
            <h2>Repairs &rarr;</h2>
            <p>
              Dont worry we will handle the repairs for you
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>

          <b>Address</b>: Jail Road, Main Line, Wardha.
      </footer>
    </div>
  )
}
